  extern char  Wpawn , Wrook  , Wknight  , Wbishop , Wqueen , Wking ;
  extern char  Bpawn , Brook , Bknight , Bbishop , Bqueen , Bking;
  extern char inputmove[100];
  extern char eatenpiece;
  extern char promotionpiece;
  extern int undoCount;
  typedef struct{
    char board[8][8];
    int movesplayed;
    int whiteeatencount;
    int blackeatencount;
    char whiteeaten[16];
    char blackeaten[16];
    int whitewin;
    int blackwin;
    int enpassCol;
    int Wkingmoved;
    int WrookmovedA;
    int WrookmovedH;
    int Bkingmoved;
    int BrookmovedA;
    int BrookmovedH;
  } game;
  extern game history[1000];
  extern game current;